database:
  host: "localhost"
  port: "3306"
  args: ""
  db: "utazon"
  user: "user"
  pass: "password"

socket:
  port: "44444"

web:
  host: "http://localhost:8000" # 接続用のリンク
  pass: "password" # Web側のパスワード

  embed: "http://localhost:8000" # 注文書に埋め込む用のリンク
