database:
  host: "localhost"
  port: "3306"
  args: ""
  db: "utazon"
  user: "user"
  pass: "password"

socket:
  port: "44444"

web:
  # Webと同じにしてください
  host: "http://localhost:8000"
  pass: "password"
