name: Utazon
version: '${version}'
main: work.utakatanet.utazonplugin.UtazonPlugin
api-version: '1.19'
authors: [Myoko]
depend:
  - EconomyUtilsAPI

commands:
  utazon:
    permission-message: "このコマンドを実行する権限がありません"

permissions:
  utazon.*:
    description: Allows all utazon commands.
    default: op
    children:
      utazon.socket: true
      utazon.reload: true
      utazon.stockgui: true

  utazon.socket:
    description: Allows /utazon socket command.
    default: op

  utazon.stockgui:
    description: Allows /utazon stockgui command.
    default: true

  utazon.reload:
    description: Allows /utazon reload command.
    default: op
